spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


    jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false

    flyway:
      enabled: true

logging:
  level:
    root: INFO

